apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-checkout-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-checkout-service
  template:
    metadata:
      labels:
        app: user-checkout-service
    spec:
      containers:
        - name: user-checkout-service
          image: sahanrandika/user-checkout-service
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: "mongodb+srv://sahanrandika28:jFtiW6foiDAafAfI@herb-cluster.5hgjz5q.mongodb.net/test"
            - name : STRIPE_PRIVATE_KEY
              value: "sk_test_51MzLbqLBzkmE9gXzZVdaGPJdv1IUo6wwxNcdQ58ZCg0zB0KPTIhlHcK7sWZexzIEKe4bYmofn8Ol2FBNCN9PHDDh003zlR5NGI"